# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="completions",
            name="agent_output",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
