# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_completions_agent_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="db_connection_uri",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_db_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
